on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test wrangler-action-for-rust
    steps:
      - name: print cargo and npm versions
        id: print-versions
        uses: alank976/wrangler-action-for-rust@main
        with:
          apiToken: foo
          # environment: dev
          publish: false
          preCommands: |
            echo "Installed wrangler version:"
            wrangler --version
            echo "Installed npm version:"
            npm --version
